### ISSUE TITLE
CalculatorBrain description is incorrect in some cases

### ISSUE THREAD

**Issue by vfonic** [ArmandGrillet/Standford-CS193P#1]
According to homework description:
`g. 7 + 9 = + 6 + 3 = would show “7 + 9 + 6 + 3 =” (25 in the display)`
`k. 4 × π = would show “4 × π =“ (12.5663706143592 in the display)`

Just wanted to let you know since I'm also having issues implementing fully correctly and I've found your code which is pretty close.

**Comment by armandgrillet** [comment]
I thought I got everything right but k is indeed not correct in my implementation! Thanks for the heads-up, I'll update my code this week-end.

**Comment by armandgrillet** [comment]
Problem solved using a variable called `isConstantPrinted`.
